localStorage.setItem('firstName', 'Paweł')
localStorage.setItem('lastName', 'Romik')
localStorage.setItem('age', 15)
localStorage.setItem('country', 'Poland')
localStorage.setItem('city', 'Opole')
console.log(localStorage)